# Generated by Django 3.0.6 on 2020-05-25 02:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(auto_created=True, unique=True, verbose_name='菜单排名')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('method', models.CharField(blank=True, max_length=20, verbose_name='菜单方法')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('mod_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 25, 10, 11, 7, 489343), verbose_name='修改时间')),
                ('author_name', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('sub_title', models.CharField(blank=True, max_length=140, verbose_name='副标题')),
                ('overview', models.CharField(blank=True, max_length=200, verbose_name='概要')),
                ('text', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modity_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.Category', verbose_name='类型')),
                ('tag', models.ManyToManyField(blank=True, related_name='tags', to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ['create_time'],
            },
        ),
    ]
