# Generated by Django 3.0.6 on 2020-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rank',
            field=models.IntegerField(auto_created=True, default=0, verbose_name='name rank'),
        ),
    ]
